### ISSUE TITLE
解析失败

### ISSUE THREAD

**Issue by SVNzK** [gaowanliang/OneDriveShareLinkPushAria2#30]
Traceback (most recent call last):
  File "/root/github/OneDriveShareLinkPushAria2/main.py", line 418, in <module>
    downloadFiles(OneDriveShareURL, None, 0, aria2Link,
  File "/root/github/OneDriveShareLinkPushAria2/main.py", line 177, in downloadFiles
    originalDir = getAria2ConfigDir(aria2URL, token)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/github/OneDriveShareLinkPushAria2/main.py", line 413, in getAria2ConfigDir
    return json.loads(c.text)["result"]["dir"]
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'result'


使用的url:
https://5vz43f.sharepoint.com/sites/free61/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Ffree61%2FShared%20Documents%2F2024%E5%B9%B4%2D5%E6%9C%88%2DGAME%2Fbb50&p=true&ga=1

可能是oneDriver换了接口?

**Comment by gaowanliang** [comment]
使用的不是分享链接，详见 #24

**Comment by kumiko42** [comment]
可能是因为忘填写RPC secret了
